const PF = {
    BANKS: {
        COLS_TOTAL: [
            'PinFin 지수',
            '시가총액',
            '예금총액',
            '대출현황',
            '잔존수',
            '신규 설치수',
            '평균 중복 타 뱅킹 사용수',
            '1인 평균 앱 이용시간',
            '전체 이용시간',
            '이용횟수',
        ], 
        NAME: {
            KB: '국민은행',
            IBK: 'IBK기업은행',
            NH: '농협',
            SHINHAN: '신한은행',
            KEB: 'KEB하나은행',
            WOORI: '우리은행',
            KDB: 'KDB산업은행',
            BS: '부산은행',
            DK: '대구은행',
            CITI: '한국씨티은행',
            SC: 'SC제일은행',
            KN: '경남은행',
            KJ: '광주은행',
            SH: '수협',
            JB: '전북은행',
            JJ: '제주은행',
            KAKAO: '카카오뱅크',
            KBANK: '케이뱅크'

        },
        PAGE: {
            COM: 'BankListCom',
            PVT: 'BankList',
            SERVICE: 'BankListService',
            NAVER: '/NaverBank/NaverBank'
        },
    },
    COLORS: [
        '#4dc9f6',
        '#f67019',
        '#f53794',
        '#537bc4',
        '#acc236',
        '#166a8f',
        '#00a950',
        '#58595b',
        '#8549ba',
        '#aaaaaa',
        '#888888',
        '#55bbbb',
        '#777fff',
        '#228fff',
        '#ccd000',
        '#3cadca',
        '#33ff33',
        '#44dddd',
        '#559999',
        '#f77777',
    ],
    LOCATIONS: [
        '서울',
        '경기',
        '강원',
        '경북',
        '경남',
        '충북',
        '충남',
        '전북',
        '전남',
        '광주',
        '대구',
        '인천',
        '울산',
        '부산',
        '대전',
        '제주',
        '세종',
    ],
};

export default PF